
import { GoogleGenAI, Type, Modality } from "@google/genai";
import { fileToBase64 } from "../utils/fileUtils";
import type { ReferenceAnalysis } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

const referenceAnalysisSchema = {
  type: Type.OBJECT,
  properties: {
    scene: { type: Type.STRING, description: 'Detailed description of the environment, background, and time of day.' },
    lighting: { type: Type.STRING, description: 'Description of the lighting setup, e.g., soft light, dramatic shadows, golden hour.' },
    camera: { type: Type.STRING, description: 'Camera details like angle, focal length, aperture, and depth of field.' },
    character: { type: Type.STRING, description: 'Description of the character including gender, pose, outfit, and emotion.' },
    color_palette: { type: Type.STRING, description: 'The dominant colors and overall color grading style.' },
    composition: { type: Type.STRING, description: 'Details about framing, rule of thirds, leading lines, and foreground/background elements.' },
    style: { type: Type.STRING, description: 'The overall artistic style, e.g., ultra-realistic, moody, cinematic, high-fashion.' },
  },
  required: ['scene', 'lighting', 'camera', 'character', 'color_palette', 'composition', 'style']
};

export async function analyzeReferenceImage(image: File): Promise<ReferenceAnalysis> {
  const { base64Data, mimeType } = await fileToBase64(image);
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-pro',
    contents: {
      parts: [
        { text: 'Analyze this reference image and output a detailed JSON object describing its visual characteristics. Follow the provided schema precisely.' },
        { inlineData: { data: base64Data, mimeType } }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: referenceAnalysisSchema,
    },
  });

  const jsonString = response.text.trim();
  try {
    return JSON.parse(jsonString) as ReferenceAnalysis;
  } catch (e) {
    console.error("Failed to parse JSON response:", jsonString);
    throw new Error("Received invalid JSON from the API.");
  }
}

export async function generateFinalImage(userImage: File, promptObject: ReferenceAnalysis): Promise<string> {
  const { base64Data, mimeType } = await fileToBase64(userImage);
  
  const detailedPrompt = `You are a master digital artist specializing in photorealistic image composition. Your task is to create a new, cinematic image.
1. **Subject's Face**: Use the face from the first provided image (the user's photo).
2. **Scene & Style**: Create the entire scene, character pose, lighting, and mood based on the following detailed JSON description:
   \`\`\`json
   ${JSON.stringify(promptObject, null, 2)}
   \`\`\`
3. **Integration**: Seamlessly integrate the user's face into this new scene. The final image must look like a single, professionally shot photograph. Pay extreme attention to matching lighting direction, color grading, skin tones, and shadows. The result should be ultra-realistic and high-end. Do not create a collage; create a new, cohesive piece of art. The output must be a single image.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: base64Data, mimeType } },
        { text: detailedPrompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
    }
  }

  throw new Error("No image was generated by the API.");
}
